import os
import subprocess
import sys

from cloudify import ctx
from cloudify.state import ctx_parameters as inputs


def install_packages(packages):
    ctx.logger.info('Installing {packages}'.format(
        ', '.join(packages),
    ))
    if not hasattr(sys, 'real_prefix'):
        raise RuntimeError('Not running inside virtualenv directory')

    pip_fpath = os.path.join(sys.prefix, 'bin', 'pip')
    cmd = [pip_fpath, 'install']
    cmd.extend(packages)
    exit_code = subprocess.call(cmd)

    ctx.logger.info('Install exit code: {0}'.format(exit_code))
    if exit_code != 0:
        raise RuntimeError('Package install ended with non zero exit code')


def regenerate_host_keys():
    # Do not regenerate moduli as it will take an excessive amount of time
    # and leave existing file alone in case it was generated by the user

    # regenerate ecdsa key
    subprocess.call(["rm", "/etc/ssh/ssh_host_ecdsa_key"])
    subprocess.call(["rm", "/etc/ssh/ssh_host_ecdsa_key.pub"])
    subprocess.call(["ssh-keygen", "-b", "521", "-f",
                     "/etc/ssh/ssh_host_ecdsa_key", "-N", '', "-t", "ecdsa"])

    # regenerate ed25519 key
    subprocess.call(["rm", "/etc/ssh/ssh_host_ed25519_key"])
    subprocess.call(["rm", "/etc/ssh/ssh_host_ed25519_key.pub"])
    subprocess.call(["ssh-keygen", "-f", "/etc/ssh/ssh_host_ed25519_key",
                     "-N", '', "-t", "ed25519"])

    # regenerate rsa key
    subprocess.call(["rm", "/etc/ssh/ssh_host_rsa_key"])
    subprocess.call(["rm", "/etc/ssh/ssh_host_rsa_key.pub"])
    subprocess.call(["ssh-keygen", "-b", "4096", "-f",
                     "/etc/ssh/ssh_host_rsa_key", "-N", '', "-t", "rsa"])

    # restart ssh
    subprocess.call(["systemctl", "restart", "sshd"])


def authorize_user_ssh_key(ssh_key):
    with open('/home/centos/.ssh/authorized_keys', 'a') as auth_handle:
        auth_handle.write('%s\n' % ssh_key)


def main():
    regenerate_host_keys()

    authorize_user_ssh_key(inputs['user_ssh_key'])

    install_packages(inputs['required_packages'].split(','))


if __name__ == '__main__':
    main()
