#! /usr/bin/env bash
CFY_BIN=/opt/cfy_cli/bin/cfy
cd ${BLUEPRINT_PATH}

# Inject the correct username
sudo sed -i "s/<<IMAGEBUILDERUSER>>/$(whoami)/" scripts/configure.py

# Use the correct credentials
export CLOUDIFY_USERNAME=${CLOUDIFY_MANAGER_USERNAME}
export CLOUDIFY_PASSWORD=${CLOUDIFY_MANAGER_PASSWORD}

# Initialise the env and upload the blueprint
${CFY_BIN} init
if [[ "${CLOUDIFY_MANAGER_SECURITY_ENABLED}" == "true" ]]; then
    export CLOUDIFY_SSL_CERT=~/cloudify/cloudify-manager-blueprints/resources/ssl/server.crt
    ${CFY_BIN} use -t 127.0.0.1 --port 443
else
    ${CFY_BIN} use -t 127.0.0.1
fi
${CFY_BIN} blueprints upload -p ${BLUEPRINT_FILE_NAME_PREFIX}_${PACKER_BUILD_NAME}.yaml -b ${BLUEPRINT_NAME}
