#! /usr/bin/env bash
for platform in aws openstack; do
  mkdir ${platform}_dependencies
  cp ${platform}-dependencies ${platform}_dependencies/setup.py
  zip -r blueprint/plugins/${platform}_dependencies.zip ${platform}_dependencies/setup.py
  rm -rf ${platform}_dependencies
done
